language: cpp

compiler:
  - clang
  - gcc

env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release

script:
  - mkdir build2
  - cd build2
  - cmake -D CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} .. && make
